SensorWeb/Controllers/UserTypeController.cs
using AutoMapper;
using Core;
using Core.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using SensorWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace SensorWeb.Controllers
{
    [Authorize]
    public class UserTypeController : BaseController
    {
        IUserTypeService _UserTypeService;
        IMapper _mapper;
        private readonly IStringLocalizer<Resources.CommonResources> _localizer;

        /// <summary>
        /// Construtor
        /// </summary>
        /// <param name="UserTypeService"></param>
        /// <param name="mapper"></param>
        /// <param name="localizer"></param>
        public UserTypeController(IUserTypeService UserTypeService,
                                  IMapper mapper,
                                  IStringLocalizer<Resources.CommonResources> localizer)
        {
            _UserTypeService = UserTypeService;
            _mapper = mapper;
            _localizer = localizer;
        }

        // GET: UserTypeController
        public ActionResult Index()
        {
            var listaUsuarios = _UserTypeService.GetAll();
            var listaUserTypeModel = _mapper.Map<List<UserTypeModel>>(listaUsuarios);

            //foreach (var UserTypeModel in listaUserTypeModel)
            //{
            //    UserTypeModel.Contact = _mapper.Map<List<ContactModel>>(_UserTypeService.GetAll())
            //}

            //Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo("en-US");
          //  ViewData["Title"] = _localizer["UserTypeTittle"];
            return View(listaUserTypeModel.OrderBy(x => x.Id));
        }

        // GET: UserTypeController/Details/5
        public ActionResult Details(int id)
        {
            UserType UserType = _UserTypeService.Get(id);
            UserTypeModel UserTypeModel = _mapper.Map<UserTypeModel>(UserType);
            return View(UserTypeModel);
        }

        // GET: UserTypeController/Create
        public ActionResult Create()
        {
            UserTypeModel user = new UserTypeModel()
            {
                Id = _UserTypeService.GetlastCode()
            };

            return View(user);
        }

        // POST: UserTypeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserTypeModel UserTypeModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UserTypeModel.Id = _UserTypeService.GetlastCode();
                    var UserType = _mapper.Map<UserType>(UserTypeModel);
                    _UserTypeService.Insert(UserType);
                }

                return RedirectToAction(nameof(Index));
            }
            catch(Exception e)
            {
                return View();
            }
        }

        // GET: UserTypeController/Edit/5
        public ActionResult Edit(int id)
        {
            UserType UserType = _UserTypeService.Get(id);
            UserTypeModel UserTypeModel = _mapper.Map<UserTypeModel>(UserType);
            return View(UserTypeModel);
        }

        // POST: UserTypeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, UserTypeModel UserTypeModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var UserType = _mapper.Map<UserType>(UserTypeModel);
                    _UserTypeService.Edit(UserType);

                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UserTypeController/Delete/5
        public ActionResult Delete(int id)
        {
            UserType UserType = _UserTypeService.Get(id);
            UserTypeModel UserTypeModel = _mapper.Map<UserTypeModel>(UserType);
            return View(UserTypeModel);
        }

        // POST: UserTypeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, UserTypeModel UserTypeModel)
        {
            try
            {
                _UserTypeService.Remove(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SensorWeb/Views/UserType/Create.cshtml
@model SensorWeb.Models.UserTypeModel
@inject SensorWeb.Resources.CommonLocalizationService localizer

<h4 class="screenTitle">@localizer.Get("UserTypeTitle") </h4>
<hr />
<div class="row screenCreate">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" readonly />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group screenCreateControls">
                <a href="@Url.Action("Index", "UserType")"><input asp-action="Index" type="button" value="@localizer.Get("BackToList")" class="btn btn-primary" /></a>
                <input type="submit" value="@localizer.Get("Create")" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<hr />

@*<div>
        <a asp-action="Index">@localizer.Get("BackToList")</a>
    </div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SensorWeb/Views/UserType/Delete.cshtml
@model SensorWeb.Models.UserTypeModel
@inject SensorWeb.Resources.CommonLocalizationService localizer


<h4 style="text-align:center">@localizer.Get("UserTypeTitle") </h4>
<hr />

<h5 style="">@localizer.Get("DeleteRegister")?</h5>
<div class="row screenCreate">
    <div class="col-md-12 formclasscreate">
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Id)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Id)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
        </dl>
    </div>
    <div class="col-md-12 ">
        <div class="form-group screenCreateControls col-md-6">
            <form asp-action="Delete">
                <input type="submit" value="@localizer.Get("Delete")" class="btn btn-danger" />
                <a asp-action="Index" class="btn btn-primary">@localizer.Get("BackToList")</a>
            </form>
        </div>
    </div>
</div>

SensorWeb/Views/UserType/Details.cshtml
@model SensorWeb.Models.UserTypeModel
@inject SensorWeb.Resources.CommonLocalizationService localizer

<h4 class="screenTitle">@localizer.Get("UserTypeTitle") </h4>
<hr />
<div class="row screenCreate">
    <div class="col-md-4">
        <form asp-action="Details">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" readonly />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group screenCreateControls">
                <a href="@Url.Action("Index", "UserType")"><input asp-action="Index" type="button" value="@localizer.Get("BackToList")" class="btn btn-primary" /></a>
                @*<input type="submit" value="@localizer.Get("Create")" class="btn btn-primary" />*@
            </div>
        </form>
    </div>
</div>
<hr />

@*<div>
        <a asp-action="Index">@localizer.Get("BackToList")</a>
    </div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SensorWeb/Views/UserType/Edit.cshtml
@model SensorWeb.Models.UserTypeModel
@inject SensorWeb.Resources.CommonLocalizationService localizer

<h4 class="screenTitle">@localizer.Get("UserTypeTitle") </h4>
<hr />
<div class="row screenCreate">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" readonly />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group screenCreateControls">
                <a href="@Url.Action("Index", "UserType")"><input asp-action="Index" type="button" value="@localizer.Get("BackToList")" class="btn btn-primary" /></a>
                <input type="submit" value="@localizer.Get("Save")" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<hr />

@*<div>
        <a asp-action="Index">@localizer.Get("BackToList")</a>
    </div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SensorWeb/Views/UserType/Index.cshtml
@model IEnumerable<UserTypeModel>

@inject SensorWeb.Resources.CommonLocalizationService localizer


<div class="page-title">
    <h3 class="breadcrumb-header">Cadastros</h3>
</div>


<div id="main-wrapper">
    <div class="row">

        <div class="col-md-12">

            <div class="card card-white">

                <div class="card-heading clearfix">

                    <table style="width: 100%;">
                        <tr>
                            <td><h4 class="card-title">@localizer.Get("UserTypeTitle")</h4></td>
                            <td style="text-align:right">

                                <a href="@Url.Action("Create", "UserType" )" title="@localizer.Get("Add new")">
                                    <button type="button" class="btn btn-success btn-sm"><i class="fas fa-plus"></i> </button>
                                </a>
                              

                            </td>
                        </tr>

                    </table>

                </div>

                <div class="card-body">

                    <div class="table-responsive">
                        <table id="example" class="display table" style="width:100%;text-align:center">
                            <thead>
                                <tr>
                                    @*<th>
                                        @Html.DisplayNameFor(modelItem => modelItem.Id)
                                    </th>*@
                                    <th>
                                        @Html.DisplayNameFor(modelItem => modelItem.Name)
                                    </th>
                                    <th class="sccentralize">
                                        @Html.DisplayNameFor(modelItem => modelItem.UpdatedAt)
                                    </th>

                                    <th style="text-align:center">
                                        @localizer.Get("Actions")
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    @*<td>
                                        @Html.DisplayFor(modelItem => item.Id)
                                    </td>*@
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                    <td class="sccentralize">
                                        @Html.DisplayFor(modelItem => item.UpdatedAtSt)
                                    </td>


                                    <td>
                                        <table style="width:100%">
                                            <tr>
                                                <td style="padding:0 4px"><a href="@Url.Action("Details", "UserType", new { id = item.Id })" title="@localizer.Get("View")"><i class="fas fa-eye"></i></a></td>
                                                <td style="padding:0 4px"><a href="@Url.Action("Edit", "UserType", new { id = item.Id })" title="@localizer.Get("Edit")"><i class="fas fa-edit" style="color:#ff6a00"></i></a></td>
                                                <td style="padding:0 4px"><a href="@Url.Action("Delete", "UserType", new { id = item.Id })" title="@localizer.Get("Delete")" style="color:#ff0000"><i class="fas fa-window-close"></i></a></td>
                                            </tr>
                                        </table>
                                    </td>

                                    <!--<td style="text-align:center">-->

                                        @*<partial name="_ListActionsControls" />*@

                                        <!--<a href="@Url.Action("Details", "UserType", new { id = item.Id })" title="@localizer.Get("View")" class="links">
                                            <img alt="List View" style="height:16px;width:23px;margin-right:15px" src="@Url.Content("~/Resources/visual.png")">
                                        </a>
                                        <a href="@Url.Action("Edit", "UserType", new { id = item.Id })" title="@localizer.Get("Edit")" class="links">
                                            <img alt="List View" style="margin-right: 15px" src="@Url.Content("~/Resources/lapis_16x16.png")">
                                        </a>

                                        <a href="@Url.Action("Delete", "UserType", new { id = item.Id })" title="@localizer.Get("Delete")" class="links">
                                            <img alt="List View" src="@Url.Content("~/Resources/exc_16x16.png")">
                                        </a>
                                    </td>
                                    <td></td>-->
                                </tr>
                                }


                                @*<tr>
                                    <td>1</td>
                                    <td>Administrador</td>
                                    <td>12/01/2022</td>
                                    <td>
                                        <table style="width:100%">
                                            <tr>
                                                <td style="padding:0 4px"><a href="#" title="detalhes"><i class="fas fa-eye"></i></a></td>
                                                <td style="padding:0 4px"><a href="#" title="editar"><i class="fas fa-edit" style="color:#ff6a00"></i></a></td>
                                                <td style="padding:0 4px"><a href="#" title="excluir" style="color:#ff0000"><i class="fas fa-window-close"></i></a></td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>*@



                            </tbody>

                        </table>
                    </div>
                </div>






            </div>
        </div>
    </div>

</div>

<!-- end page main wrapper -->
<div class="page-footer">
    <p>IotNest/Vibração &copy; <span class="current-year"></span>. Conteúdo de uso exclusivo.</p>
</div>

SensorWeb/Views/UserType/IndexOriginal.cshtml
@model IEnumerable<UserTypeModel>

@inject SensorWeb.Resources.CommonLocalizationService localizer


<h4 style="color:white; text-align:center">@localizer.Get("UserTypeTitle") </h4>
<hr />
<p>
    <a href="@Url.Action("Create", "UserType" )" title="@localizer.Get("Add new")">
        <img src="@Url.Content("~/Resources/new_rec_32x32.png")" />
    </a>
</p>
<table class="table sclistTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(modelItem => modelItem.Id)
            </th>
            <th>
                @Html.DisplayNameFor(modelItem => modelItem.Name)
            </th>
            <th class="sccentralize">
                @Html.DisplayNameFor(modelItem => modelItem.UpdatedAt)
            </th>

            <th style="text-align:center">
                @localizer.Get("Actions")
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody class="sctbodyresult">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td class="sccentralize">
                    @Html.DisplayFor(modelItem => item.UpdatedAtSt)
                </td>
                <td style="text-align:center">

                    @*<partial name="_ListActionsControls" />*@

                    <a href="@Url.Action("Details", "UserType", new { id = item.Id })" title="@localizer.Get("View")" class="links">
                        <img alt="List View" style="height:16px;width:23px;margin-right:15px" src="@Url.Content("~/Resources/visual.png")">
                    </a>
                    <a href="@Url.Action("Edit", "UserType", new { id = item.Id })" title="@localizer.Get("Edit")" class="links">
                        <img alt="List View" style="margin-right: 15px" src="@Url.Content("~/Resources/lapis_16x16.png")">
                    </a>

                    <a href="@Url.Action("Delete", "UserType", new { id = item.Id })" title="@localizer.Get("Delete")" class="links">
                        <img alt="List View" src="@Url.Content("~/Resources/exc_16x16.png")">
                    </a>
                </td>
                <td></td>
            </tr>
        }
    </tbody>
</table>