SensorWeb/Controllers/DeviceController.cs
using AutoMapper;
using Core;
using Core.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using SensorWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Drawing;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.Extensions.Logging;
using QRCoder;
using Microsoft.AspNetCore.Authorization;
using Core.Utils;
using SensorService;
using System.Security.Claims;
using Core.DTO;
using Dapper;
using Microsoft.Extensions.Options;
using System.Text;

namespace SensorWeb.Controllers
{
    [Authorize]
    public class DeviceController : BaseController
    {
        IDeviceService _deviceService;
        IUserService _userService;
        ICompanyService _companyService;
        IMotorService _motorService;
        IMapper _mapper;

        private readonly IStringLocalizer<Resources.CommonResources> _localizer;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ILogger<DeviceController> _logger;
        private readonly WebsiteSettings _siteSettings;

        /// <summary>
        /// Construtor
        /// </summary>
        /// <param name="DeviceService"></param>
        /// <param name="mapper"></param>
        /// <param name="localizer"></param>
        public DeviceController(IDeviceService DeviceService,
                                IUserService UserService, 
                                ICompanyService CompanyService,
                                IMotorService MotorService,
                                  IMapper mapper,
                                  IStringLocalizer<Resources.CommonResources> localizer,
                                  IWebHostEnvironment webHostEnvironment,
                                  ILogger<DeviceController> logger,
                                  IOptions<WebsiteSettings> siteSettings)
        {
            _deviceService = DeviceService;
            _userService = UserService;
            _companyService = CompanyService;
            _motorService = MotorService;
            _mapper = mapper;
            _localizer = localizer;
            _webHostEnvironment = webHostEnvironment;
            _logger = logger;
            _siteSettings = siteSettings.Value;
        }

        // GET: DeviceController
        public ActionResult Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _userService.Get(Convert.ToInt32(userId));
            var userCompany = user.Contact.CompanyId;
            var companies = _companyService.GetAll().Where(x => x.ParentCompanyId == userCompany).ToList();

            var listaDevices = _deviceService.GetAll().ToList();

            if (user.UserType.Name == Constants.Roles.Supervisor || user.UserType.Name == Constants.Roles.User)
            {
                listaDevices = listaDevices.Where(x => x.CompanyId == userCompany).ToList();
            }
            else if (user.UserType.Name == Constants.Roles.Sysadmin)
            {
                listaDevices = listaDevices.Where(x => x.CompanyId == userCompany || companies.Any(y => y.Id == x.CompanyId)).ToList();
            }

            var listaDeviceModel = _mapper.Map<List<DeviceModel>>(listaDevices);

            foreach (var DeviceModel in listaDeviceModel)
            {
                DeviceModel.QrCodeImg = QrCodeGen($"{_siteSettings.WebsiteURL}/Login?qr={ObfuscateDeviceCode(DeviceModel.Code)}");
            }

            return View(listaDeviceModel.OrderBy(x => x.Id));
        }

        // GET: DeviceController/Details/5
        public ActionResult Details(int id)
        {
            Device Device = _deviceService.Get(id);
            DeviceModel deviceModel = _mapper.Map<DeviceModel>(Device);
            //ViewData["imgQrCode"] = deviceModel.Tag + ".png";
            //ViewData["imgQrCode"] = Convert.ToBase64String(QrCodeGen(deviceModel.Tag));
            if (deviceModel != null && !String.IsNullOrEmpty(deviceModel.Code))
                deviceModel.QrCodeImg = QrCodeGen($"{_siteSettings.WebsiteURL}/Login?qr={ObfuscateDeviceCode(deviceModel.Code)}");

            return View(deviceModel);
        }

        public ActionResult Create()
        {
            //DeviceModel Device = new DeviceModel()
            //{
            //    Id = _DeviceService.GetlastCode()
            //};

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCopy(DeviceModel model)
        {
            model.Id = 0;

            return View("Create", model);
        }

        // POST: DeviceController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Constants.Roles.Administrator)]
        public ActionResult Create(DeviceModel deviceModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    deviceModel.Id = _deviceService.GetlastCode();
                    var Device = _mapper.Map<Device>(deviceModel);
                    _deviceService.Insert(Device);

                    _logger.LogInformation($"Insert Device OK");
                    string webRootPath = _webHostEnvironment.WebRootPath;
                    string contentRootPath = _webHostEnvironment.ContentRootPath;

                    _logger.LogInformation($"getPath OK");

                    string path = "";
                    path = Path.Combine(webRootPath, "Resources", "QrCodeTags/");

                    _logger.LogInformation(path);

                    if (deviceModel != null)
                        ViewData["imgQrCode"] = QrCodeGen($"{_siteSettings.WebsiteURL}/Login?qr={ObfuscateDeviceCode(deviceModel.Code)}");


                }

                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                return View();
            }
        }

        public ActionResult ActionQR(string dCode, bool obfs = false)
        {
            if (obfs == true)
                dCode = UnobfuscateDeviceCode(dCode);

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _userService.Get(Convert.ToInt32(userId));
            var userCompany = user.Contact.CompanyId;
            var companies = _companyService.GetAll().Where(x => x.ParentCompanyId == userCompany).ToList();
            var device = _deviceService.GetByCode(dCode);

            ViewBag.UserHasPermission = false;
            ViewBag.DeviceId = 0;
            ViewBag.MotorId = 0;
            ViewBag.DeviceCode = dCode;

            if (device != null)
            {
                if (user.UserType.Name == Constants.Roles.Administrator)
                {
                    ViewBag.UserHasPermission = true;
                }
                else if (user.UserType.Name == Constants.Roles.Supervisor || user.UserType.Name == Constants.Roles.User)
                {
                    if (device.CompanyId == userCompany)
                    {
                        ViewBag.UserHasPermission = true;
                    }
                }
                else if (user.UserType.Name == Constants.Roles.Sysadmin)
                {
                    if (device.CompanyId == userCompany || companies.Any(c => c.Id == device.CompanyId))
                    {
                        ViewBag.UserHasPermission = true;
                    }
                }
            }
            
            if (ViewBag.UserHasPermission == true)
            {
                ViewBag.DeviceId = device.Id;
                ViewBag.DeviceName = device.Tag;
                ViewBag.MotorId = device.DeviceMotorId != null ? device.DeviceMotor?.MotorId ?? 0 : 0;
            }

            return View();
        }

        public byte[] QrCodeGen(string qrTexto)
        {
            QRCodeGenerator qrGenerator = new QRCodeGenerator();
            QRCodeData qrCodeData = qrGenerator.CreateQrCode(qrTexto, QRCodeGenerator.ECCLevel.Q);
            QRCode qrCode = new QRCode(qrCodeData);
            Bitmap qrCodeImage = qrCode.GetGraphic(20);
            return BitmapToBytes(qrCodeImage);
        }
        private static Byte[] BitmapToBytes(Bitmap img)
        {
            using (MemoryStream stream = new MemoryStream())
            {
                img.Save(stream, System.Drawing.Imaging.ImageFormat.Png);
                return stream.ToArray();
            }
        }

        // GET: DeviceController/Edit/5
        public ActionResult Edit(int id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _userService.Get(Convert.ToInt32(userId));
            var listaCompany = _companyService.GetAll();

            listaCompany = FilterCompaniesByUser(user, listaCompany);

            Device device = _deviceService.Get(id);

            DeviceModel deviceModel = _mapper.Map<DeviceModel>(device);
            //ViewData["imgQrCode"] = deviceModel.Tag + ".png";
            if (deviceModel != null)
            {
                deviceModel.QrCodeImg = QrCodeGen($"{_siteSettings.WebsiteURL}/Login?qr={ObfuscateDeviceCode(deviceModel.Code)}");
                deviceModel.Companies = listaCompany
                    .Select(y => new SelectListItemDTO()
                    {
                        Key = y.Id,
                        Value = y.TradeName
                    }).Distinct().ToList();
            }
            return View(deviceModel);
        }

        public ActionResult EditMobile(int id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = _userService.Get(Convert.ToInt32(userId));
            var listaCompany = _companyService.GetAll();

            listaCompany = FilterCompaniesByUser(user, listaCompany);

            Device device = _deviceService.Get(id);

            DeviceModel deviceModel = _mapper.Map<DeviceModel>(device);

SensorWeb/Views/Device/ActionQR.cshtml
@inject SensorWeb.Resources.CommonLocalizationService localizer
@inject Core.Service.ICompanyService companyService

@{
    Layout = "~/Views/Shared/_Layout_Mobile.cshtml";
}

<h4 class="screenTitle">Escolher Ação</h4>
<hr />
<div class="row">
    <div class="col-md-12">

        @if (ViewBag.UserHasPermission == true)
        {
            <div class="col-md-12" style="text-align:center;margin-bottom:20px;">
                <h3>@ViewBag.DeviceName</h3>
                <h4>@ViewBag.DeviceCode</h4>
            </div>

            @if (ViewBag.DeviceId != 0)
            {
                <div class="col-md-12" style="text-align:center;margin-bottom:20px;">
                    <a href="@Url.Action("EditMobile", "Device", new { id = (int)ViewBag.DeviceId })" class="btn btn-primary"
                       style="color:white;font-weight:bold;width: 250px;">
                        Cadastro de Sensor
                    </a>
                </div>
            }

            @if (ViewBag.DeviceId != 0 && ViewBag.MotorId != 0)
            {
                <div class="col-md-12" style="text-align:center;margin-bottom:20px;">
                    <a href="@Url.Action("IndexMobile", "DeviceMeasure", new { codeAttempt = ViewBag.DeviceCode })" class="btn btn-primary"
                       style="color:white;font-weight:bold;width: 250px;">
                        Configuração de Sensor
                    </a>
                </div>
            }

            @if ((User.IsInRole("Sysadmin") || User.IsInRole("Administrador") || User.IsInRole("Supervisor")) && ViewBag.MotorId != 0)
            {
                <div class="col-md-12" style="text-align:center;margin-bottom:20px;">
                    <a href="@Url.Action("EditMobile", "Motor", new { id = (int)ViewBag.MotorId, mdc = ViewBag.DeviceCode  })" class="btn btn-primary"
                       style="color:white;font-weight:bold;width: 250px;">
                        Cadastro de Equipamento
                    </a>
                </div>
            }
            else if (ViewBag.MotorId == 0)
            {
                <div class="col-md-12" style="text-align:center;margin-bottom:20px;">
                    <a href="@Url.Action("IndexMobile", "Motor", new { mdc = ViewBag.DeviceCode  })" class="btn btn-primary"
                       style="color:white;font-weight:bold;width: 250px;">
                        Cadastro de Equipamento
                    </a>
                </div>
            }
        }
        else
        {
            <div class="col-md-12" style="text-align:center;">
                <h2 style="color:crimson;">Você não possui permissão para visualizar este sensor.</h2>
            </div>
        }

    </div>
</div>
<hr />


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

SensorWeb/Views/Device/Create.cshtml
@using System.Security.Claims
@model SensorWeb.Models.DeviceModel
@inject SensorWeb.Resources.CommonLocalizationService localizer
@inject Core.Service.ICompanyService companyService

@{
    string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
}

<h4 class="screenTitle">@localizer.Get("DeviceTitle") </h4>
<hr />
<div class="row screenCreate">
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group col-md-6">
                <label asp-for="Tag" class="control-label"></label>
                <input asp-for="Tag" class="form-control" />
                <span asp-validation-for="Tag" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>

            <div class="form-group col-md-4">
                <label asp-for="CompanyId" class="control-label"></label>
                @Html.DropDownListFor(model => model.CompanyId, new SelectList(companyService.GetQueryDropDownListStrict(userId), "Key", "Value"),
                                      @localizer.Get("CompanySelect"), new Dictionary<string, object> { { "class", "form-control" } })
                <span asp-validation-for="CompanyId" class="text-danger"></span>
            </div>

           <div class="row" style="display:none;">
                <div class="form-group col-md-3" style="display: grid;">
                    <label class="control-label">Frequencia</label>
                    <select name="Frequency" id="Frequency" class="form-control" asp-for="Frequency" style="width:100%">
                        <option value="">Selecionar</option>
                        <option value="15">15Hz</option>
                        <option value="20">20Hz</option>
                        <option value="25">25Hz</option>
                        <option value="30">30Hz</option>
                        <option value="35">35Hz</option>
                        <option value="40">40Hz</option>
                        <option value="45">45Hz</option>
                        <option value="50">50Hz</option>
                        <option value="55">55Hz</option>
                        <option value="60">60Hz</option>
                        <option value="65">65Hz</option>
                    </select>
                    <span asp-validation-for="Frequency" class="text-danger"></span>
                </div>

                <div class="form-group col-md-3" style="display: grid;">
                    <label class="control-label">BDR</label>
                    <select name="Bdr" id="Bdr" class="form-control" asp-for="Bdr" style="width:100%">
                        <option value="">Selecionar</option>
                        <option value="52">52Hz</option>
                        <option value="104">104Hz</option>
                        <option value="208">208Hz</option>
                        <option value="417">417Hz</option>
                        <option value="833">833Hz</option>
                        <option value="1.667">1.667Hz</option>
                        <option value="3.333">3.333Hz</option>
                        <option value="6.667">6.667Hz</option>
                        <option value="13.333">13.333Hz</option>
                        <option value="26.667">26.667Hz</option>
                    </select>
                    <span asp-validation-for="Bdr" class="text-danger"></span>
                </div>

                <div class="form-group col-md-3" style="display: grid;">
                    <label class="control-label">CutOff</label>
                    <select name="Cutoff" id="Cutoff" class="form-control" asp-for="Cutoff" style="width:100%">
                        <option value="">Selecionar</option>
                        <option value="6.667">6.667Hz</option>
                        <option value="2.667">2.667Hz</option>
                        <option value="1.333">1.333Hz</option>
                        <option value="593">593Hz</option>
                        <option value="267">267Hz</option>
                        <option value="133">133Hz</option>
                        <option value="67">67Hz</option>
                        <option value="33">33Hz</option>
                    </select>
                    <span asp-validation-for="Cutoff" class="text-danger"></span>
                </div>

                <div class="form-group col-md-3" style="display: grid;">
                    <label class="control-label">LPF</label>
                    <select name="Lpf" id="Lpf" style="width:100%" asp-for="Lpf" class="form-control">
                        <option value="">Selecionar</option>
                        <option value="1">HPF - High Pass Filter </option>
                        <option value="2">LPF - Low Pass Filter</option>
                        <option value="3">LPF + LPF2_Off</option>
                    </select>
                    <span asp-validation-for="Lpf" class="text-danger"></span>
                </div>
           </div>

            <div class="row" style="display:none;">
                <div class="form-group col-md-3" style="display: grid;">
                    <label class="control-label">Lines</label>
                    <select name="Lines" id="Lines" asp-for="Lines" style="width:100%" class="form-control">
                        <option value="">Selecionar</option>
                        <option value="512">512</option>
                        <option value="1024">1024</option>
                        <option value="2048">2048</option>
                        <option value="3456">3456</option>
                        <option value="4096">4096</option>
                        <option value="6144">6144</option>
                        <option value="8192">8192</option>
                        <option value="10240">10240</option>
                        <option value="16384">16384</option>
                        <option value="30080">30080</option>
                    </select>
                    <span asp-validation-for="Lines" class="text-danger"></span>
                </div>

                <div class="form-group col-md-3" style="display: grid;">
                    <label class="control-label">Eixos</label>
                    <select name="Axies" id="Axies" asp-for="Axies" style="width:100%" class="form-control">
                        <option value="">Selecionar</option>
                        <option value="1">Eixo X</option>
                        <option value="2">Eixo Y</option>
                        <option value="3">Eixo Z</option>
                        <option value="4">Eixos X Y Z</option>
                    </select>
                    <span asp-validation-for="Axies" class="text-danger"></span>
                </div>

                <div class="form-group col-md-3" style="display: grid;">
                    <label class="control-label">Temperatura</label>
                    <input value="25" asp-for="Temperature" name="Temperature" id="Temperature" class="form-control" />
                    <span asp-validation-for="Temperature" class="text-danger"></span>
                </div>

                <div class="form-group col-md-3" style="display: grid;">
                    <label class="control-label">RMS</label>
                    <input value="0 g" asp-for="Rms" id="Rms" name="Rms" class="form-control" />
                    <span asp-validation-for="Rms" class="text-danger"></span>
                </div>
            </div>
            
            <div class="row" style="display:none;">
                <div class="form-group col-md-3" style="display: grid;">
                    <label class="control-label">Bateria</label>
                    <input value="100%" asp-for="Battery" name="Battery" id="Battery" class="form-control" />
                    <span asp-validation-for="Battery" class="text-danger"></span>
                </div>

                <div class="form-group col-md-3" style="display: grid;">
                    <label class="control-label">Timer</label>
                    <input placeholder="Horas" asp-for="Hours" id="Hours" name="Hours" class="form-control" />
                    <span asp-validation-for="Hours" class="text-danger"></span>
                </div>

                <div class="form-group col-md-3" style="display: grid;">
                    <label class="control-label">Global em velocidade</label>
                    <input placeholder="Mínimo mm/s" asp-for="VelocityMin" id="VelocityMin" name="VelocityMin" class="form-control" />
                    <span asp-validation-for="VelocityMin" class="text-danger"></span>
                </div>

                <div class="form-group col-md-3" style="display: grid;">
                    <label class="control-label">Global em velocidade</label>
                    <input placeholder="Máximo mm/s" asp-for="VelocityMax" id="VelocityMin" name="VelocityMax" class="form-control" />
                    <span asp-validation-for="VelocityMax" class="text-danger"></span>
                </div>
            </div>

            <div class="row" style="display:none;">
                <div class="form-group col-md-3" style="display: grid;">
                    <label class="control-label">Global em aceleração</label>
                    <input placeholder="Mínimo mm/s" asp-for="AccelerationMin" name="AccelerationMin" id="AccelerationMin" class="form-control" />
                    <span asp-validation-for="AccelerationMin" class="text-danger"></span>
                </div>

                <div class="form-group col-md-3" style="display: grid;">
                    <label class="control-label">Global em aceleração</label>
                    <input placeholder="Máximo mm/s" asp-for="AccelerationMax" id="AccelerationMax" name="AccelerationMax" class="form-control" />
                    <span asp-validation-for="AccelerationMax" class="text-danger"></span>
                </div>

                <div class="form-group col-md-3" style="display: grid;">
                    <label class="control-label">Fator de Crista</label>
                    <input placeholder="Mínimo mm/s" asp-for="CrestFactorMin" id="CrestFactorMin" name="CrestFactorMin" class="form-control" />
                    <span asp-validation-for="CrestFactorMin" class="text-danger"></span>
                </div>

                <div class="form-group col-md-3" style="display: grid;">
                    <label class="control-label">Fator de Crista</label>
                    <input placeholder="Máximo mm/s" asp-for="CrestFactorMax" id="CrestFactorMax" name="CrestFactorMax" class="form-control" />
                    <span asp-validation-for="CrestFactorMax" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="form-group screenCreateControls col-md-6">
                    <a href="@Url.Action("Index", "Device")"><input asp-action="Index" type="button" value="@localizer.Get("BackToList")" class="btn btn-primary" /></a>
                    <input type="submit" value="@localizer.Get("Create")" class="btn btn-primary" />
                </div>
                <div class="form-group screenCreateControls col-md-6" style="text-align: right;">
                    <button type="button" class="btn btn-secondary" disabled>Copiar</button>
                </div>
            </div>
            
        </form>
    </div>
</div>
<hr />

@*<div>
        <a asp-action="Index">@localizer.Get("BackToList")</a>
    </div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SensorWeb/Views/Device/Delete.cshtml
@model SensorWeb.Models.DeviceModel
@inject SensorWeb.Resources.CommonLocalizationService localizer


<h4 style="text-align:center">@localizer.Get("DeviceTitle") </h4>
<hr />

<h5 style="">@localizer.Get("DeleteRegister")?</h5>
<div class="row screenCreate">
    <div class="col-md-12 formclasscreate">
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Id)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Id)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Tag)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Code)
            </dd>
        </dl>
    </div>
    <div class="col-md-12 ">
        <div class="form-group screenCreateControls col-md-6">
            <form asp-action="Delete">
                <input type="submit" value="@localizer.Get("Delete")" class="btn btn-danger" />
                <a asp-action="Index" class="btn btn-primary">@localizer.Get("BackToList")</a>
            </form>
        </div>
    </div>
</div>